-- ==============================================================================
-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS E STORAGE NO SUPABASE
-- LOJA SILVA E SOL
-- ==============================================================================
-- Instruções:
-- 1. Abra o painel do seu projeto no Supabase (https://supabase.com/dashboard)
-- 2. No menu lateral esquerdo, clique no ícone "SQL Editor"
-- 3. Clique em "+ New query", cole todo este código e clique no botão "Run" (Executar)
-- ==============================================================================

-- 1. ADICIONAR COLUNAS FALTANTES NA TABELA PRODUCTS (SE NECESSÁRIO)
ALTER TABLE IF EXISTS public.products 
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS fotos text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS em_destaque boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Criar tabela products se não existir
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  title text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL DEFAULT 0,
  category text,
  image_url text,
  fotos text[] DEFAULT '{}',
  em_destaque boolean DEFAULT true,
  is_active boolean DEFAULT true
);

-- 2. TABELA DE BANNERS
ALTER TABLE IF EXISTS public.banners 
  ADD COLUMN IF NOT EXISTS description text;

CREATE TABLE IF NOT EXISTS public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  title text,
  subtitle text,
  description text,
  image_url text NOT NULL,
  button_text text,
  button_link text,
  display_order integer DEFAULT 1,
  is_active boolean DEFAULT true
);

-- 3. TABELA DE CÍRCULOS DE DESTAQUE (CATEGORIAS NA HOME)
CREATE TABLE IF NOT EXISTS public.circulos_destaque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  nome text NOT NULL,
  img_url text NOT NULL,
  link text,
  ordem integer DEFAULT 0
);

-- Inserir círculos padrão caso a tabela esteja vazia
INSERT INTO public.circulos_destaque (nome, img_url, link, ordem)
SELECT nome, img_url, link, ordem FROM (
  VALUES 
    ('Promoções', 'logo.jpg.jpg', 'produtos.html?cat=Promocoes', 1),
    ('Sungas', 'logo.jpg.jpg', 'produtos.html?cat=Sungas', 2),
    ('Regatas', 'logo.jpg.jpg', 'produtos.html?cat=Regatas', 3),
    ('Bolsas', 'logo.jpg.jpg', 'produtos.html?cat=Bolsas', 4),
    ('Kimono', 'logo.jpg.jpg', 'produtos.html?cat=Kimono', 5),
    ('Kits', 'logo.jpg.jpg', 'produtos.html?cat=Kits', 6)
) AS v(nome, img_url, link, ordem)
WHERE NOT EXISTS (SELECT 1 FROM public.circulos_destaque LIMIT 1);

-- 4. ATIVAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.circulos_destaque ENABLE ROW LEVEL SECURITY;

-- 5. POLÍTICAS DE ACESSO PARA TABELA PRODUCTS
DROP POLICY IF EXISTS "Leitura publica de produtos" ON public.products;
CREATE POLICY "Leitura publica de produtos" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Inserir produtos" ON public.products;
CREATE POLICY "Inserir produtos" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Atualizar produtos" ON public.products;
CREATE POLICY "Atualizar produtos" ON public.products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Excluir produtos" ON public.products;
CREATE POLICY "Excluir produtos" ON public.products FOR DELETE USING (true);

-- 6. POLÍTICAS DE ACESSO PARA TABELA BANNERS
DROP POLICY IF EXISTS "Leitura publica de banners" ON public.banners;
CREATE POLICY "Leitura publica de banners" ON public.banners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Inserir banners" ON public.banners;
CREATE POLICY "Inserir banners" ON public.banners FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Atualizar banners" ON public.banners;
CREATE POLICY "Atualizar banners" ON public.banners FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Excluir banners" ON public.banners;
CREATE POLICY "Excluir banners" ON public.banners FOR DELETE USING (true);

-- 7. POLÍTICAS DE ACESSO PARA TABELA CIRCULOS_DESTAQUE
DROP POLICY IF EXISTS "Leitura publica de circulos" ON public.circulos_destaque;
CREATE POLICY "Leitura publica de circulos" ON public.circulos_destaque FOR SELECT USING (true);

DROP POLICY IF EXISTS "Inserir circulos" ON public.circulos_destaque;
CREATE POLICY "Inserir circulos" ON public.circulos_destaque FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Atualizar circulos" ON public.circulos_destaque;
CREATE POLICY "Atualizar circulos" ON public.circulos_destaque FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Excluir circulos" ON public.circulos_destaque;
CREATE POLICY "Excluir circulos" ON public.circulos_destaque FOR DELETE USING (true);

-- 8. CONFIGURAÇÃO DO BUCKET DE STORAGE PARA FOTOS (midias)
INSERT INTO storage.buckets (id, name, public)
VALUES ('midias', 'midias', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage para o bucket 'midias'
DROP POLICY IF EXISTS "Leitura publica de midias" ON storage.objects;
CREATE POLICY "Leitura publica de midias"
ON storage.objects FOR SELECT
USING (bucket_id = 'midias');

DROP POLICY IF EXISTS "Upload publico de midias" ON storage.objects;
CREATE POLICY "Upload publico de midias"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'midias');

DROP POLICY IF EXISTS "Atualizacao publica de midias" ON storage.objects;
CREATE POLICY "Atualizacao publica de midias"
ON storage.objects FOR UPDATE
USING (bucket_id = 'midias');

DROP POLICY IF EXISTS "Exclusao publica de midias" ON storage.objects;
CREATE POLICY "Exclusao publica de midias"
ON storage.objects FOR DELETE
USING (bucket_id = 'midias');
